Algoritmo "crescente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2025
Var
x,y:inteiro


Inicio
escreval("Digite dois numeros:")
leia(x)
leia(Y)
enquanto x <> y faca
   se x < y entao
      escreval("CRESCENTE!")
   senao
        escreval("DECRESCENTE!")
   fimse
   escreval("Digite dois numeros:")
   leia(x)
   leia(Y)
fimenquanto

Fimalgoritmo