Algoritmo "divisao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2025
Var
n,x,y,i,p:inteiro
divisao:real

Inicio
escreva("Digite um número:")
leia(n)
para i de 1 ate n faca

              escreva("Entre com o numerador:")
              leia(x)
              escreva("Entre com o denominador:")
              leia(y)
              se y = 0 entao
                 escreval("Divisão nula")
              senao
                   divisao <- x/y
                   escreval(divisao)
              fimse

fimpara





Fimalgoritmo