Algoritmo "fatorial"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2025
Var
n,i,resultado:inteiro


Inicio
escreva("Digite um número natural entre 1 a 15:")
leia(n)
enquanto n > 15 faca
escreva("Digite um número natural entre 1 a 15:")
leia(n)
fimenquanto
resultado<- 1
para i de 1 ate n faca
     resultado <- resultado * i

fimpara
escreval("FATORIAL =",resultado)

Fimalgoritmo