Algoritmo "media_ponderada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2025
Var
//n,i,p:inteiro
//x,media,y,z,q:real
n,i:inteiro
a,b,c,media:real
Inicio
//escreva("Digite um número:")
//leia(n)
//para p de 1 ate n faca
   //para i de 1 ate 3 faca
        //escreva("Digite um número para média ponderada:")
        //leia(x)
        //se i = 1 entao
           //y <- x * 2
        //senao
             //se i = 2 entao
                //q <- x * 3
             //senao
                  //se i = 3 entao
                     //z <- x * 5

                  //fimse
             //fimse
        //fimse
   //fimpara
   //media <- (y + q + z)/10
   //escreval("média",media)
//fimpara

escreva("Quantos casos você vai digitar:")
leia(n)
para i de 1 ate n faca
     escreval("digite tres numeros:")
     leia(a)
     leia(b)
     leia(c)
     media<- (a*2 + b*3 + c*5)/10
     escreval("media = ",media:3:1)
fimpara
































Fimalgoritmo