Algoritmo "pares_consecutivos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2025
Var
x,soma:inteiro


Inicio
escreva("Digite um numero inteiro:")
leia (x)
enquanto x <> 0 faca
   se x mod 2 <> 0 entao
      x <- x + 1
   fimse
    soma <- 5 * x + 20
    escreval(soma)
    escreva("Digite um numero inteiro:")
    leia (x)
fimpara
Fimalgoritmo