Algoritmo "senha_fixa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2025
Var
senha:inteiro


Inicio
escreval("Digite a senha:")
leia(senha)
enquanto senha <> 2002 faca
       escreval("Senha Invalida! Tente novamente:")
       leia(senha)
       
fimenquanto
escreva("Acesso permitido!")

Fimalgoritmo