Algoritmo "sequencia_impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2025
Var
x,i:inteiro

Inicio
escreva("Digite um número:")
leia(x)
para i de 1 ate x faca
     se x % <> 0 entao
        escreval(i)
     fimse

fimpara


Fimalgoritmo