Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2025
Var
n,soma,i:inteiro


Inicio
escreva("Digite um número para a tabuada:")
leia(n)
para i de 1 até 10 faca
     soma <- n * i
     escreval(n,"x",i,"=",soma)
fimpara


Fimalgoritmo